[package]
name = "fund-simulator-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
claim = "0.5.0"
clap = { version = "4.4.6", features = ["derive", "cargo"] }
typed_floats = "0.1.37"

[dev-dependencies]
pretty_assertions = "1.4.0"
assert_float_eq = "1.1.3" 
