version: "3.8"

services:
  web:
    build: .
    image: fundsimulatorrs
    volumes:
      - ./real_distributions:/app/real_distributions
    ports:
      - "3000:3000"
    env_file:
      - config/default.env

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  db-data:
